/**
 * Provinces and major cities of Pakistan for dropdowns in company and customer forms.
 */

export const PAKISTAN_PROVINCES = [
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
  "Islamabad",
  "Gilgit-Baltistan",
  "Azad Jammu and Kashmir",
] as const;

export type PakistanProvince = (typeof PAKISTAN_PROVINCES)[number];

/** Cities by province (key must match PAKISTAN_PROVINCES) */
export const CITIES_BY_PROVINCE: Record<string, readonly string[]> = {
  Punjab: [
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Gujranwala",
    "Sialkot",
    "Sargodha",
    "Bahawalpur",
    "Gujrat",
    "Sahiwal",
    "Sheikhupura",
    "Jhelum",
    "Dera Ghazi Khan",
    "Kasur",
    "Mianwali",
    "Okara",
    "Rahim Yar Khan",
    "Sadiqabad",
    "Wah Cantonment",
    "Chiniot",
    "Kamoke",
    "Hafizabad",
    "Khanewal",
    "Lodhran",
    "Vehari",
    "Narowal",
    "Pakpattan",
    "Mandi Bahauddin",
    "Jhang",
    "Toba Tek Singh",
    "Attock",
    "Murree",
    "Taxila",
    "Other",
  ],
  Sindh: [
    "Karachi",
    "Hyderabad",
    "Sukkur",
    "Larkana",
    "Nawabshah",
    "Mirpurkhas",
    "Jacobabad",
    "Shikarpur",
    "Khairpur",
    "Dadu",
    "Thatta",
    "Badin",
    "Sanghar",
    "Umerkot",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Matiari",
    "Jamshoro",
    "Kotri",
    "Other",
  ],
  "Khyber Pakhtunkhwa": [
    "Peshawar",
    "Mardan",
    "Abbottabad",
    "Mingora",
    "Kohat",
    "Bannu",
    "Dera Ismail Khan",
    "Charsadda",
    "Nowshera",
    "Swabi",
    "Mansehra",
    "Haripur",
    "Malakand",
    "Chitral",
    "Other",
  ],
  Balochistan: [
    "Quetta",
    "Gwadar",
    "Turbat",
    "Chaman",
    "Khuzdar",
    "Sibi",
    "Loralai",
    "Zhob",
    "Dera Bugti",
    "Other",
  ],
  Islamabad: ["Islamabad", "Other"],
  "Gilgit-Baltistan": [
    "Gilgit",
    "Skardu",
    "Chilas",
    "Diamer",
    "Ghizer",
    "Hunza",
    "Nagar",
    "Astore",
    "Other",
  ],
  "Azad Jammu and Kashmir": [
    "Muzaffarabad",
    "Mirpur",
    "Rawalakot",
    "Kotli",
    "Bagh",
    "Bhimber",
    "Neelum",
    "Other",
  ],
};

export function getCitiesForProvince(province: string): readonly string[] {
  return CITIES_BY_PROVINCE[province] ?? [];
}
